import { BsTypescript } from 'react-icons/bs';
import { FaLinux } from 'react-icons/fa';
import { FaCss3Alt, FaHtml5, FaLaravel, FaNodeJs, FaPhp, FaReact } from 'react-icons/fa6';
import { SiDocker, SiExpress, SiGit, SiGithub, SiMongodb, SiMysql } from 'react-icons/si';
import type { Skill } from './types';

// B4 fixed: static skills now use `iconComponent` (the resolved React component),
// matching the runtime `Skill` type. SkillChip and CodeTabBar both read `iconComponent`.
export const skills: Skill[] = [
  {
    name: 'HTML 5',
    iconComponent: FaHtml5,
    fileName: 'index.html',
    lang: 'html',
    color: '#e44d26',
    mode: 'code',
    code: [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `  <head>`,
      `    <meta charset="UTF-8" />`,
      `    <title>Portfolio</title>`,
      `  </head>`,
      `  <body>`,
      `    <h1>Hello World 👋</h1>`,
      `  </body>`,
      `</html>`,
    ],
  },
  {
    name: 'CSS',
    iconComponent: FaCss3Alt,
    fileName: 'styles.css',
    lang: 'css',
    color: '#264de4',
    mode: 'code',
    code: [
      `:root {`,
      `  --primary: #264de4;`,
      `  --radius: 0.5rem;`,
      `}`,
      ``,
      `.card {`,
      `  border-radius: var(--radius);`,
      `  backdrop-filter: blur(12px);`,
      `  transition: transform 0.3s ease;`,
      `}`,
    ],
  },
  {
    name: 'TypeScript',
    iconComponent: BsTypescript,
    fileName: 'utils.ts',
    lang: 'typescript',
    color: '#3178c6',
    mode: 'code',
    code: [
      `type Skill = {`,
      `  name: string;`,
      `  level: "junior" | "mid" | "senior";`,
      `};`,
      ``,
      `const getSkill = (`,
      `  skills: Skill[],`,
      `  name: string`,
      `): Skill | undefined =>`,
      `  skills.find((s) => s.name === name);`,
    ],
  },
  {
    name: 'React',
    iconComponent: FaReact,
    fileName: 'App.tsx',
    lang: 'tsx',
    color: '#61dafb',
    mode: 'code',
    code: [
      `import { useState } from "react";`,
      ``,
      `export default function App() {`,
      `  const [count, setCount] = useState(0);`,
      ``,
      `  return (`,
      `    <button`,
      `      onClick={() => setCount(c => c + 1)}`,
      `    >`,
      `      Count: {count}`,
      `    </button>`,
      `  );`,
      `}`,
    ],
  },
  {
    name: 'Node.js',
    iconComponent: FaNodeJs,
    fileName: 'server.js',
    lang: 'javascript',
    color: '#8cc84b',
    mode: 'code',
    code: [
      `import { createServer } from "http";`,
      ``,
      `const PORT = process.env.PORT ?? 3000;`,
      ``,
      `const server = createServer((req, res) => {`,
      `  res.writeHead(200, {`,
      `    "Content-Type": "text/plain",`,
      `  });`,
      `  res.end("Hello from Node.js!");`,
      `});`,
      ``,
      `server.listen(PORT, () => {`,
      `  console.log(\`Running on \${PORT}\`);`,
      `});`,
    ],
  },
  {
    name: 'Express',
    iconComponent: SiExpress,
    fileName: 'app.js',
    lang: 'javascript',
    color: '#eeeeee',
    mode: 'code',
    code: [
      `import express from "express";`,
      ``,
      `const app = express();`,
      `app.use(express.json());`,
      ``,
      `app.get("/users", async (req, res) => {`,
      `  const users = await db.find({});`,
      `  res.json({ data: users });`,
      `});`,
      ``,
      `app.listen(3000, () =>`,
      `  console.log("Server ready on :3000")`,
      `);`,
    ],
  },
  {
    name: 'MySQL',
    iconComponent: SiMysql,
    fileName: 'queries.sql',
    lang: 'sql',
    color: '#00758f',
    mode: 'code',
    code: [
      `SELECT`,
      `  u.id,`,
      `  u.name,`,
      `  COUNT(o.id) AS total_orders`,
      `FROM users u`,
      `LEFT JOIN orders o`,
      `  ON o.user_id = u.id`,
      `WHERE u.created_at > NOW() - INTERVAL 30 DAY`,
      `GROUP BY u.id`,
      `ORDER BY total_orders DESC`,
      `LIMIT 10;`,
    ],
  },
  {
    name: 'MongoDB',
    iconComponent: SiMongodb,
    fileName: 'queries.ts',
    lang: 'typescript',
    color: '#4db33d',
    mode: 'code',
    code: [
      `import { MongoClient } from "mongodb";`,
      ``,
      `const client = new MongoClient(process.env.MONGO_URI!);`,
      `const db     = client.db("portfolio");`,
      ``,
      `const users = await db`,
      `  .collection("users")`,
      `  .find({ active: true })`,
      `  .sort({ createdAt: -1 })`,
      `  .limit(10)`,
      `  .toArray();`,
    ],
  },
  {
    name: 'PHP',
    iconComponent: FaPhp,
    fileName: 'api.php',
    lang: 'php',
    color: '#777bb4',
    mode: 'code',
    code: [
      `<?php`,
      ``,
      `function getUser(int $id): array {`,
      `  $stmt = $pdo->prepare(`,
      `    "SELECT * FROM users WHERE id = ?"`,
      `  );`,
      `  $stmt->execute([$id]);`,
      `  return $stmt->fetch();`,
      `}`,
    ],
  },
  {
    name: 'Laravel',
    iconComponent: FaLaravel,
    fileName: 'UserController.php',
    lang: 'php',
    color: '#ff2d20',
    mode: 'code',
    code: [
      `class UserController extends Controller`,
      `{`,
      `  public function index(): JsonResponse`,
      `  {`,
      `    $users = User::query()`,
      `      ->latest()`,
      `      ->paginate(15);`,
      ``,
      `    return response()->json($users);`,
      `  }`,
      `}`,
    ],
  },
  {
    name: 'Git',
    iconComponent: SiGit,
    fileName: 'terminal',
    lang: 'bash',
    color: '#f05032',
    mode: 'terminal',
    commands: [
      { kind: 'comment', text: '# Initialise repo & stage files' },
      { kind: 'command', text: 'git init && git add .' },
      { kind: 'output', text: 'Initialized empty Git repository in .git/' },
      { kind: 'blank' },
      { kind: 'command', text: 'git commit -m "feat: initial commit"' },
      { kind: 'output', text: '[main (root-commit) a1b2c3d] feat: initial commit' },
      { kind: 'output', text: ' 3 files changed, 42 insertions(+)' },
      { kind: 'blank' },
      { kind: 'comment', text: '# Branch, merge & rebase' },
      { kind: 'command', text: 'git checkout -b feat/skills-section' },
      { kind: 'output', text: "Switched to a new branch 'feat/skills-section'" },
      { kind: 'blank' },
      { kind: 'command', text: 'git rebase main' },
      { kind: 'output', text: 'Successfully rebased and updated refs/heads/feat/skills-section.' },
      { kind: 'blank' },
      { kind: 'comment', text: '# Stash work in progress' },
      { kind: 'command', text: "git stash push -m 'wip: half-done navbar'" },
      {
        kind: 'output',
        text: 'Saved working directory and index state On feat: wip: half-done navbar',
      },
      { kind: 'blank' },
      { kind: 'command', text: 'git log --oneline --graph' },
      { kind: 'output', text: '* a1b2c3d (HEAD -> main) feat: initial commit' },
      { kind: 'output', text: '* 9f8e7d6 chore: project scaffold' },
    ],
  },
  {
    name: 'GitHub',
    iconComponent: SiGithub,
    fileName: 'terminal',
    lang: 'bash',
    color: '#e0e0e0',
    mode: 'terminal',
    commands: [
      { kind: 'comment', text: '# Create repo & push' },
      { kind: 'command', text: 'gh repo create portfolio --public --source=.' },
      { kind: 'output', text: '✓ Created repository user/portfolio on GitHub' },
      { kind: 'output', text: '✓ Pushed commits to github.com/user/portfolio' },
      { kind: 'blank' },
      { kind: 'comment', text: '# Open a pull request' },
      { kind: 'command', text: 'gh pr create --title "feat: skills section" --fill' },
      { kind: 'output', text: 'Creating pull request for feat/skills into main' },
      { kind: 'output', text: 'https://github.com/user/portfolio/pull/7' },
      { kind: 'blank' },
      { kind: 'comment', text: '# List & merge open PRs' },
      { kind: 'command', text: 'gh pr list' },
      { kind: 'output', text: 'ID  TITLE                STATUS  BRANCH' },
      { kind: 'output', text: '#7  feat: skills section  OPEN   feat/skills' },
      { kind: 'blank' },
      { kind: 'command', text: 'gh pr merge 7 --squash --delete-branch' },
      { kind: 'output', text: '✓ Squashed and merged pull request #7' },
      { kind: 'output', text: '✓ Deleted branch feat/skills' },
      { kind: 'blank' },
      { kind: 'comment', text: '# Trigger a workflow' },
      { kind: 'command', text: 'gh workflow run deploy.yml' },
      { kind: 'output', text: '✓ Created workflow_dispatch event for deploy.yml' },
    ],
  },
  {
    name: 'Docker',
    iconComponent: SiDocker,
    fileName: 'terminal',
    lang: 'bash',
    color: '#2496ed',
    mode: 'terminal',
    commands: [
      { kind: 'comment', text: '# Build the image' },
      { kind: 'command', text: 'docker build -t portfolio:latest .' },
      { kind: 'output', text: '[+] Building 11.4s (9/9) FINISHED' },
      { kind: 'output', text: ' => [1/4] FROM node:20-alpine              2.1s' },
      { kind: 'output', text: ' => [2/4] COPY package*.json ./            0.0s' },
      { kind: 'output', text: ' => [3/4] RUN npm ci                       8.6s' },
      { kind: 'output', text: ' => exporting to image                     0.3s' },
      { kind: 'blank' },
      { kind: 'comment', text: '# Run detached & check logs' },
      { kind: 'command', text: 'docker run -d -p 3000:3000 --name app portfolio:latest' },
      { kind: 'output', text: 'a1b2c3d4e5f67890a1b2c3d4e5f67890' },
      { kind: 'blank' },
      { kind: 'command', text: 'docker logs app --tail 5' },
      { kind: 'output', text: 'Server listening on http://0.0.0.0:3000' },
      { kind: 'blank' },
      { kind: 'comment', text: '# Compose up all services' },
      { kind: 'command', text: 'docker compose up -d' },
      { kind: 'output', text: ' ✔ Container db     Started    0.4s' },
      { kind: 'output', text: ' ✔ Container app    Started    0.6s' },
      { kind: 'output', text: ' ✔ Container nginx  Started    0.7s' },
      { kind: 'blank' },
      { kind: 'command', text: 'docker ps' },
      { kind: 'output', text: 'CONTAINER   IMAGE              STATUS        PORTS' },
      { kind: 'output', text: 'nginx       nginx:alpine       Up 2 seconds  0.0.0.0:80->80/tcp' },
      {
        kind: 'output',
        text: 'app         portfolio:latest   Up 2 seconds  0.0.0.0:3000->3000/tcp',
      },
      { kind: 'output', text: 'db          mysql:8            Up 2 seconds  3306/tcp' },
    ],
  },
  {
    name: 'Linux',
    iconComponent: FaLinux,
    fileName: 'terminal',
    lang: 'bash',
    color: '#fcc624',
    mode: 'terminal',
    commands: [
      { kind: 'comment', text: '# Explore the file system' },
      { kind: 'command', text: 'ls -la' },
      { kind: 'output', text: 'drwxr-xr-x  8 user user 4096 Mar 16 03:42 .' },
      { kind: 'output', text: '-rw-r--r--  1 user user  220 Mar 16 03:42 .bashrc' },
      { kind: 'output', text: '-rwxr-xr-x  1 user user  512 Mar 16 03:42 deploy.sh' },
      { kind: 'blank' },
      { kind: 'comment', text: '# Permissions & execution' },
      { kind: 'command', text: 'chmod +x deploy.sh && ./deploy.sh' },
      { kind: 'output', text: 'Deploying to production...' },
      { kind: 'output', text: '✓ Build complete' },
      { kind: 'output', text: '✓ Service restarted' },
      { kind: 'blank' },
      { kind: 'comment', text: '# Process & port inspection' },
      { kind: 'command', text: 'ps aux | grep node' },
      { kind: 'output', text: 'user   1234  0.1  1.2  node server.js' },
      { kind: 'blank' },
      { kind: 'command', text: 'lsof -i :3000' },
      { kind: 'output', text: 'COMMAND  PID  USER  TYPE  NODE  NAME' },
      { kind: 'output', text: 'node    1234  user  IPv4  TCP   *:3000 (LISTEN)' },
      { kind: 'blank' },
      { kind: 'comment', text: '# System resources' },
      { kind: 'command', text: 'df -h / && free -h' },
      { kind: 'output', text: 'Filesystem  Size  Used  Avail  Use%  Mounted on' },
      { kind: 'output', text: '/dev/sda1    50G   18G    32G   36%  /' },
      { kind: 'output', text: '              total   used   free' },
      { kind: 'output', text: 'Mem:           16G   5.2G   9.4G' },
    ],
  },
];
