export const AppNavigation = {
  HOME: '#home',
  SKILLS: '#skills',
  ABOUT: '#about',
  PORTFOLIO: '#portfolio',
  EXPERIENCE: '#experience',
  TESTIMONIALS: '#testimonials',
  CONTACT: '#contact',
  ADMIN: '/admin',
  AUTH: '/auth',
  DASHBOARD: '/dashboard',
  A_SKILLS: '/dashboard/skills',
  A_CONTACT: '/dashboard/contact',
  A_PORTFOLIO: '/dashboard/portfolio',
} as const;
